# Case studies



## Case studies on data visualization


```{r child-vis, results='asis', echo = FALSE}
url <- "https://raw.githubusercontent.com/sebastiansauer/Lehre/main/Material/yacsdas-vis.md"
childtext <- readLines(url)
cat(childtext, sep="\n")
```








## Case studies on explorative data analysis


```{r child-eda, results='asis', echo = FALSE}
url <- "https://raw.githubusercontent.com/sebastiansauer/Lehre/main/Material/yacsdas-EDA.md"
childtext <- readLines(url)
cat(childtext, sep="\n")
```








## Case studies on linear modesl




```{r child2, results='asis', echo = FALSE}
url <- "https://raw.githubusercontent.com/sebastiansauer/Lehre/main/Material/yacsdas-lm.md"
childtext <- readLines(url)
cat(childtext, sep="\n")
```



## Case studies on machine learning using tidymodels



```{r child3, results='asis', echo = FALSE}
url <- "https://raw.githubusercontent.com/sebastiansauer/Lehre/main/Material/yacsdas-tidymodels.md"
childtext <- readLines(url)
cat(childtext, sep="\n")
```

