# Goals in statistics

## Overview



```{mermaid}

flowchart LR
  A{Goals} --> B(describe)
  A --> C(predict)
  A --> D(explain)
  B --> E(distribution)
  B --> F(assocation)
  B --> G(extrapolation)
  C --> H(point estimate)
  C --> I(interval)
  D --> J(causal inference)
  D --> K(population)
  D --> L(latent construct)

```

:::{.callout-note}
Note that "goals" do not exist in the world. We make them up in our heads.
Hence, they have no ontological existence, they are epistemological beasts.
This entails that we are free to devise goals as we wish, provided we can convince ourselves and other souls of the utility of our creativity.
:::



## Further reading

@hernan_second_2019 distinguish:

Hernán et al. (2019) distinguish:

- *Description*: "How can women aged 60–80 years with stroke history be partitioned in classes defined by their characteristics?"

- *Prediction*: "What is the probability of having a stroke next year for women with certain characteristics?"

- *Causal inference*: "Will starting a statin reduce, on average, the risk of stroke in women with certain characteristics?"


@gelman_regression_2021, chap. 1.1 proposes the three "challenges" of statistical inference.



